package watchword;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Evprog
 */
public class pm extends javax.swing.JFrame {
    DefaultTableModel model;
    
    
    
    

    /**
     * Creates new form pm
     */
    public pm() {
        initComponents();
        jTextArea2.setEditable(false);
        jTextArea1.setEditable(false);
        model = (DefaultTableModel) jTable1.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 255));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 800));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Click to Generate a password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter any 3 dight number to be include at the end of your password");

        jLabel5.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        jLabel5.setText("Sentence to remember your password below");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Your final password");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("List of converted alphabets:\na- @\nb- 6\nc- (\ne- 3\nf- {\ng- 8 \nh- #\ni- !\nj- ;\nk- <\nl- |\no- 0\nq- ?\ns- $\nt- +\nx- *\ny- /\nz- %\n\nalphabets that can't be changed till now:\n\nd,m,n,p,r,u,v,w");
        jScrollPane3.setViewportView(jTextArea2);

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setText("Save it");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel7)
                        .addGap(43, 43, 43)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(242, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );

        jTabbedPane1.addTab("Start", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Password"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PASSWORD", "SENTENCE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Show");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(0, 490, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addContainerGap(294, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Customize"));

        jLabel2.setText("Enter you own 4 Word sentence");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton2.setText("Generate final password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Any three digit number");

        jButton7.setText("Save");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton7)))
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButton2)
                .addGap(38, 38, 38)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customize", jPanel3);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("**IMPORTANT**\n******/\n        This will only let you generate a password of length 7 letters.\n            Password = (First 2 letters encrypted)+(2 Upper case letters)+(3 digits)\n                                                          *******\\\n\n1.You must include following alphabet in order to genrate a secure password due to the \nlimitation of availability of closest identical symbol encryption.(This part is under\ndevelopment)\n\n2.A three digit numebr is essential as a secure password must contain numerical digits\nalso, although numbers are helpful in increasing length as well security.\n\n3.Right now you can create only 7 digit password(whivh inlcudes two encrypted alphabets\nfollowed by upper case alphabets and finally your desired 3 digits).\n\n\nList of converted alphabets:\na- @\nb- 6\nc- (\ne- 3\nf- {\ng- 8 \nh- #\ni- !\nj- ;\nk- <\nl- |\no- 0\nq- ?\ns- $\nt- +\nx- *\ny- /\nz- %\n\nalphbets that can't be changed till now:\n\nd,m,n,p,r,u,v,w");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("HowTo", jPanel6);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Password Recovery"));

        jLabel4.setText("Please enter your Email");

        jButton3.setText("Send Saved password");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("(This will send you a email including your generated password)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jButton3)))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("More", jPanel5);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("About WatchWord", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
      
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        try {
            new Datab();
           Statement st = Datab.conn.createStatement();
           String str=null;
           ResultSet rs = st.executeQuery("select *from WWtable ORDER BY RAND()");
           while(rs.next()){
           
           str=rs.getString("Sentence");
           jTextField1.setText(str);
           
           
           
           }
           //MAGIC CODE,
         
 int l = str.length();

 char ch[]=new char[4];
 int k=0;
 ch[k++]=str.charAt(0);
   System.out.print(ch[k]);

 for(int i=1;i<l;i++){
    
 char x = str.charAt(i);

 if (x==' ')
    ch[k++]=str.charAt(i+1);
  //          System.out.print(str.charAt(i+1));
    
    
    }
String s="";
String csh=String.valueOf(ch);
//System.out.print(csh);
for(int r=0;r<2;r++)
{
	int chh=csh.charAt(r);
        
        //NO CASES FOR UPPERCASE STILL THINKING ABOUT THAT :(
switch(chh)
{
         //cases for lower case letters AND SOME ALPHABET CANT BE CHANGED.... KEEP THINKING
	case 'a':
	s=s+"@";
	break;
        
        case 'b':
	s=s+"6";
	break;
        
        case 'c':
	s=s+"(";
	break;
        
        case 'd':
	s=s+"d";
	break;
        
        case 'e':
	s=s+"[";
	break;
        
        case 'f':
	s=s+"{";
	break;
        
        case 'g':
	s=s+"8";
	break;
        
        case 'h':
	s=s+"#";
	break;
        
        case 'i':
	s=s+"!";
	break;
        
        case 'j':
	s=s+";";
	break;
        
        case 'k':
	s=s+"<";
	break;
        
        case 'l':
	s=s+"|";
	break;
        
        case 'm':
	s=s+"m";
	break;
        
        case 'n':
	s=s+"n";
	break;
        
        case 'o':
	s=s+"0";
	break;
        
        case 'p':
	s=s+"p";
	break;
        
        case 'q':
	s=s+"?";
	break;
        
        case 'r':
	s=s+"r";
	break;
        
        case 's':
	s=s+"$";
	break;
        
        case 't':
	s=s+"+";
	break;
        
        case 'u':
	s=s+"u";
	break;
        
        case 'v':
	s=s+"v";
	break;
        
        case 'w':
	s=s+"w";
	break;
        
        case 'x':
	s=s+"*";
	break;
        
        case 'y':
	s=s+"y";
	break;
        
        case 'z':
	s=s+"%";
	break;
        
        //UPPERCASES
        case 'A':
	s=s+"A";
	break;
        
        case 'B':
	s=s+"B";
	break;
        
        case 'C':
	s=s+"C";
	break;
        
        case 'D':
	s=s+"D";
	break;
        
        case 'E':
	s=s+"E";
	break;
        
        case 'F':
	s=s+"F";
	break;
        
        case 'G':
	s=s+"G";
	break;
        
        case 'H':
	s=s+"H";
	break;
        
        case 'I':
	s=s+"I";
	break;
        
        case 'J':
	s=s+"J";
	break;
        
        case 'K':
	s=s+"K";
	break;
        
        case 'L':
	s=s+"1";
	break;
        
        case 'M':
	s=s+"M";
	break;
        
        case 'N':
	s=s+"N";
	break;
        
        case 'O':
	s=s+"O";
	break;
        
        case 'P':
	s=s+"P";
	break;
        
        case 'Q':
	s=s+"Q";
	break;
        
        case 'R':
	s=s+"r";
	break;
        
        case 'S':
	s=s+"s";
	break;
        
        case 'T':
	s=s+"T";
	break;
        
        case 'U':
	s=s+"U";
	break;
        
        case 'V':
	s=s+"V";
	break;
        
        case 'W':
	s=s+"W";
	break;
        
        case 'X':
	s=s+"X";
	break;
        
        case 'Y':
	s=s+"Y";
	break;
        
        case 'Z':
	s=s+"Z";
	break;
        
        
        
        
        
        
        
}	

	
}
String ss="";
for(int r=2;r<4;r++)
{
    ss=ss+String.valueOf(csh.charAt(r));
}

String pass=s+ss+jTextField2.getText();
jTextField6.setText(pass);



        }catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String cstmone=jTextField3.getText();

        int l = cstmone.length();

        char ch[]=new char[4];
        int k=0;
        ch[k++]=cstmone.charAt(0);
        System.out.print(ch[k]);

        for(int i=1;i<l;i++){

            char x = cstmone.charAt(i);

            if (x==' ')
            ch[k++]=cstmone.charAt(i+1);
            //          System.out.print(str.charAt(i+1));

        }

        String s="";
        String csh=String.valueOf(ch);
        //System.out.print(csh);
        for(int r=0;r<2;r++)
        {
            int chh=csh.charAt(r);

            //NO CASES FOR UPPERCASE STILL THINKING ABOUT THAT :(
                switch(chh)
                {
                    //cases for lower case letters AND SOME ALPHABET CANT BE CHANGED.... KEEP THINKING
                    case 'a':
                    s=s+"@";
                    break;

                    case 'b':
                    s=s+"6";
                    break;

                    case 'c':
                    s=s+"(";
                    break;

                    case 'd':
                    s=s+"d";
                    break;

                    case 'e':
                    s=s+"3";
                    break;

                    case 'f':
                    s=s+"{";
                    break;

                    case 'g':
                    s=s+"8";
                    break;

                    case 'h':
                    s=s+"#";
                    break;

                    case 'i':
                    s=s+"!";
                    break;

                    case 'j':
                    s=s+";";
                    break;

                    case 'k':
                    s=s+"<";
                    break;

                    case 'l':
                    s=s+"|";
                    break;

                    case 'm':
                    s=s+"m";
                    break;

                    case 'n':
                    s=s+"n";
                    break;

                    case 'o':
                    s=s+"0";
                    break;

                    case 'p':
                    s=s+"p";
                    break;

                    case 'q':
                    s=s+"?";
                    break;

                    case 'r':
                    s=s+"r";
                    break;

                    case 's':
                    s=s+"$";
                    break;

                    case 't':
                    s=s+"+";
                    break;

                    case 'u':
                    s=s+"u";
                    break;

                    case 'v':
                    s=s+"v";
                    break;

                    case 'w':
                    s=s+"w";
                    break;

                    case 'x':
                    s=s+"*";
                    break;

                    case 'y':
                    s=s+"/";
                    break;

                    case 'z':
                    s=s+"%";
                    break;

                    //UPPERCASES
                    case 'A':
                    s=s+"A";
                    break;

                    case 'B':
                    s=s+"B";
                    break;

                    case 'C':
                    s=s+"C";
                    break;

                    case 'D':
                    s=s+"D";
                    break;

                    case 'E':
                    s=s+"E";
                    break;

                    case 'F':
                    s=s+"F";
                    break;

                    case 'G':
                    s=s+"G";
                    break;

                    case 'H':
                    s=s+"H";
                    break;

                    case 'I':
                    s=s+"I";
                    break;

                    case 'J':
                    s=s+"J";
                    break;

                    case 'K':
                    s=s+"K";
                    break;

                    case 'L':
                    s=s+"1";
                    break;

                    case 'M':
                    s=s+"M";
                    break;

                    case 'N':
                    s=s+"N";
                    break;

                    case 'O':
                    s=s+"O";
                    break;

                    case 'P':
                    s=s+"P";
                    break;

                    case 'Q':
                    s=s+"Q";
                    break;

                    case 'R':
                    s=s+"r";
                    break;

                    case 'S':
                    s=s+"s";
                    break;

                    case 'T':
                    s=s+"T";
                    break;

                    case 'U':
                    s=s+"U";
                    break;

                    case 'V':
                    s=s+"V";
                    break;

                    case 'W':
                    s=s+"W";
                    break;

                    case 'X':
                    s=s+"X";
                    break;

                    case 'Y':
                    s=s+"Y";
                    break;

                    case 'Z':
                    s=s+"Z";
                    break;

                }

            }

            String ss="";
            for(int r=2;r<4;r++)
            {
                ss=ss+String.valueOf(csh.charAt(r));
            }

            String pass=s+ss+jTextField4.getText();
            jTextField7.setText(pass);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try{
        new Datab();
        Statement st = Datab.conn.createStatement();
        st.executeUpdate("Insert into PMgrtable(SENTENCE,PASSWORD)values('"+jTextField1.getText()+"','"+jTextField6.getText()+"')");
        System.out.println("Record Updated");
        
        }catch(Exception e)
        {
        System.out.println(e);}
        
    
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
        try {
            new Datab();
           Statement st = Datab.conn.createStatement();
           
           ResultSet rs = st.executeQuery("select *from PMgrtable");
           
           while(rs.next()){
          model.addRow(new Object[]{rs.getString("PASSWORD"),rs.getString("SENTENCE")});
           
           
           }
        }catch(Exception e){}
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
        try {
            new Datab();
           Statement st = Datab.conn.createStatement();
           
           ResultSet rs = st.executeQuery("select *from PMgrtable");
           
           while(rs.next()){
               
             model.addRow(new Object[]{rs.getString("PASSWORD"),rs.getString("SENTENCE")});
         
         
           
           }
        }catch(Exception e){}
           
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          int row=jTable1.getSelectedRow();
        String str=(String) model.getValueAt(row,0);
        try{
        new Datab();
        Statement st = Datab.conn.createStatement();
        st.executeUpdate("delete from  PMgrtable where SENTENCE ='"+str+"'");
        st.executeUpdate("delete from  PMgrtable where PASSWORD ='"+str+"'");
        System.out.println("Record Updated");
        
        }catch(Exception e)
        {
        System.out.println(e);}
        
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
         try{
        new Datab();
        Statement st = Datab.conn.createStatement();
        st.executeUpdate("Insert into PMgrtable(SENTENCE,PASSWORD)values('"+jTextField3.getText()+"','"+jTextField7.getText()+"')");
        System.out.println("Record Updated");
        
        }catch(Exception e)
        {
        System.out.println(e);}
        
        
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
        try {
            new Datab();
           Statement st = Datab.conn.createStatement();
           
           ResultSet rs = st.executeQuery("select *from PMgrtable");
           
           while(rs.next()){
          model.addRow(new Object[]{rs.getString("PASSWORD"),rs.getString("SENTENCE")});
           
           
           }
        }catch(Exception e){}
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
